index.js
lib/proto/parse-options.js
tests/lib/proto/parse-options.js

In the loadUrl function there is an explicit check for false as a means to disable the scrollTo behavior however if the scrollTo option is passed to the constructor as false the gaud statement was converting false to 0.

prevent scrollTo from being converted from false to 0

---

README.md
example/example.js
example/index.html
example/page2.html
package.json

This adds examples to `/example`. This shows that the plugin right now is at a state that doesn't actually work:
I've removed the failing test now so the test suite should pass, but that's no indicator that the project is in a working state.

Add examples, remove failing test

---

lib/events/trigger.js
tests/lib/events.js

Events triggered on top level elements (such as window or document)
lead to a HierarchyRequestError due to a fix in IE browsers
where dispatchEvent does not fire if an element is not in the DOM.
The current test is simply to check for the existence of parentNode
However, this means top level elements get added to itself, causing
the error.
The proposed fix simply tests for top level elements in the test.

[FIX] #39 - events on top level

---

lib/proto/parse-options.js

`options.analytics()` didn't have any param. so `ga("send", "pageview", {"page": options.url, "title": options.title})` got an error `Cannot read property 'url' of undefined`.
I fixed it by replaced with `ga("send", "pageview", {"page": location.pathname, "title": document.title})`.

fixed an error when using pjax with google analytics

---

README.md
lib/proto/parse-options.js
lib/request.js
tests/lib/proto/parse-options.js
tests/lib/request.js

Add cacheBust option

---

index.js
lib/proto/refresh.js

Hi,
I made two changes here:
1. Implement @robinnorth's suggestion here https://github.com/MoOx/pjax/pull/36 for refresh.
2. Handle attributes without any values (e.g. `itemscope` was causing an issue).
Let me know any feedback!
Thanks.

Update refresh and handle attributes without values

---

tests/lib/request.js

This property is only used in the tests. It doesn't exist in Safari 8 and before, so where it's not available this patch polyfills it, allowing the test to continue.

Polyfill XHR.responseURL so tests pass in old Safari

---

index.js

It used to be fixed a long time ago, but was perhaps merged away...

Fix bug on IE11 preventing from ajax page refresh

---

lib/request.js

Make it more compatible with the jQuery PJAX and lets the server choose to optimize the response. Sending the list of selectors would be nice, too.

Send the PJAX header with request

---

example/example.js
example/index.html
example/page2.html
index.js

Hi, I added `this.parseDOM(document)` to the `onSwitch()` callback. This fixes https://github.com/MoOx/pjax/issues/72
Although it works for me, the tests wouldn't run on my machine so if anyone could help test it, I'd appreciate it. _Edit: seems Travis helped._

Asynchronous switch functions

---

lib/proto/parse-options.js
lib/switches.js

Add switchElementsAlt() to the default switches

---

lib/proto/attach-form.js
lib/proto/attach-link.js

Closes #62.
With this PR, you can access the element that triggered the `pjax:send` event with `event.triggerElement`.

Pass the element that triggered Pjax to the pjax:send event

---

README.md
index.js
lib/proto/parse-options.js
lib/request.js

Add timeout for XHR requests

---

package.json

How to cut a release?
See https://github.com/MoOx/npmpub#usage
In short:
make a commit where your bump the package.json number and create a CHANGELOG.md section, then run `npm run release` (or `yarn release`).

Use npmpub like it should since testling is gone

---

index.js
lib/request.js

Fixes #7
This checks for redirects by looking for the following, in sequence:
- `XMLHttpRequest.responseURL`
- the `X-PJAX-URL` header (like jquery-pjax)
- the `X-XHR-Redirected-To` header (like Turbolinks)

Add checks for XHR redirects

---

lib/switches.js

Clone attribute nodes before setting on `oldEl` to prevent the following error:
`
DOMException: Failed to execute 'setNamedItem' on 'NamedNodeMap': The node provided is an attribute node that is already an attribute of another Element; attribute nodes must be explicitly cloned.
`

Fix DOMException in switchElementsAlt() (fixes #103)

---

README.md
index.js
lib/proto/parse-options.js
tests/lib/proto/parse-options.js

- Save scroll position with history
Save scroll position when navigating away from a page, and restore it when navigating back to that page.
Fixes #30.
- Scroll to element position when URL contains a hash
When the URL contains a hash, try to find the corresponding element, and if found, scroll to its position.
Based on darylteo/pjax@4893a2a6574b3490396f83a1863499e8a9ba171e
Fixes #22.

Enhance scrolling behavior

---

lib/proto/attach-form.js
lib/proto/attach-link.js
package.json
tests/lib/proto/attach-form.js
tests/lib/proto/attach-link.js

When submitting a form, subsequent requests keep the `requestMethod` and `requestPayload`s; this causes the form to "autosubmit" with the previous values when you load it again.
This PR resets the request options so that subsequent non-form requests go back to using the defaults.

Reset requestOptions after form submission is complete

---

index.js
lib/util/contains.js
tests/lib/util/contains.js

- Only blur element if it's contained by one of the selectors
Previously, Pjax would blur (remove focus) from the active element regardless of where it was on the page. This commit restricts that to happen only if the active element is contained by one of the elements represented by options.selectors, because only those are affected by Pjax.
Fixes #4
- Remove a redundant call to .blur()

Fix element blurring (removing focus)

---

README.md
index.js
lib/proto/handle-response.js
lib/send-request.js
tests/lib/proto/handle-response.js

* Move the XHR callback to a separate file
* Trigger an error event if the response cannot be parsed.
Fixes #123.

Handle XHR response error

---

README.md
index.d.ts
lib/switches.js
tests/lib/switches.js

This adds a new default switch which is functionally the same as the `outerHTML` switch, but uses `Node.replaceChild()` instead of `outerHTML`, so it doesn't require `switchElementsAlt`.

Add replaceNode switch

---

index.d.ts
lib/proto/attach-form.js
lib/proto/handle-response.js
lib/send-request.js
tests/lib/proto/handle-response.js

Instead of cloning `this.options` again in `handle-response.js`, pass the options object from `send-request.js`. This way, `pjax.state.options` will also have the request options.

Use the same options object in handle-response as in send-request

---

index.d.ts
lib/proto/attach-form.js
lib/send-request.js
tests/lib/proto/attach-form.js

If the form's `enctype` attribute is set to `multipart/form-data`, use `FormData` to encode the form's elements.
Fixes #132.

Add the option to use FormData to encode the form elements

---

lib/proto/attach-form.js

* Fix a bug where the value of `<option>` would not get sent if falsy
According to the spec, the value attribute should be sent if it exists, even if it's falsy.
* Don't send an `<option>` tag if it's disabled, even if it's selected.
Fixes #158.

Fix parsing values of option elements in forms

---

lib/send-request.js

Ensure correct XHR encoding for multipart/form-data forms

---

lib/proto/attach-form.js
tests/lib/proto/attach-form.js

Let the browser take care of when to do implicit submission.
Fixes #181.

Remove keyup event listener for forms

---

lib/eval-script.js
tests/lib/eval-scripts.js

* Set the id of the insert <script>.
* Check if the <script> still exists before trying to remove it.
Fixes #185.

Fix evalScripts()

---

index.js
tests/lib/proto/handle-response.js

Handle non-string HTML passed to loadContent()
